### ISSUE TITLE
Thiếu sofa_id khi lấy danh sách các giải đấu theo từng mùa giải của 1 đội bóng

### ISSUE THREAD

**Issue by haipv-ptit** [haipv-ptit/Football#1]
* leagues/get/by?season_id=1&team_id=1
(Lấy danh sách các giải đấu mà đội team_id = 1 tham dự trong mùa giải season_id = 1)
Response data trả về bị thiếu trường sofa_id cho LeagueSeason

**Comment by daothanh** [comment]
Đã update thêm leagueSeaons và seasons
